### ISSUE TITLE
Add CMS

### ISSUE THREAD

**Issue by danirukun** [watsonindustries/hololivefanbooth#14]
Candidates:
- https://www.sanity.io/
- https://strapi.io/

Some more alternatives: https://docs.astro.build/en/guides/cms/

**Comment by GoldElysium** [comment]
Having tried a lot of CMSs for the HoloEN Fan Website, Strapi and PayloadCMS were the standouts. Strapi wasn't chosen because the pricing structure, back then you only got something like 3 admin users and other limits, but that isn't the case anymore. 
Content type building in Strapi is more user friendly compared to Payload, because you can do it in admin ui instead of only in code. However extending Strapi with custom functionality is harder imo.

I'd recommend Strapi if you need something quick, but I think Payload is a better choice longterm because of its customizability.

If you want, you could extend [HoloENFans/hef-website-cms](https://github.com/HoloENFans/hef-website-cms) with whatever you need, DM me on Discord in that case.

**Comment by danirukun** [comment]
@GoldElysium the big factor that played a role was the pricing: Payload does not have a free cloud tier, so even for a small project like the fanbooth marketing website, we need to invest some time into self-hosting. Maybe it's fine when there is a larger, more complex project.   But I agree it is a bit more customisable, though we don't have any project of that complexity yet.

**Comment by GoldElysium** [comment]
If you use [HoloENFans/hef-website-cms](https://github.com/HoloENFans/hef-website-cms), you don't have to deal with the hosting. Otherwise I can still host it for you if you want, the server has unused resources anyway.
Looking at Strapi's website, they also don't have an open free tier? Sanity does have a free tier.
